export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const PUT_DATA_SUCCESS = "PUT_DATA_SUCCESS";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const LOGIN_DATA_SUCCESS = "LOGIN_DATA_SUCCESS";
export const AUTHENTICATE_DATA_SUCCESS = "AUTHENTICATE_DATA_SUCCESS";
